kind: pipeline
name: default

steps:
- name: foo
  image: alpine
  commands:
  - touch hello.txt

- name: bar
  image: alpine
  commands:
  - ls hello.txt

- name: build
  image: golang:alpine
  commands:
  - echo $$KEY
  - pwd
  - ls
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o app .
  - cp ./app /drone/
  - ls -lsr /drone/
  - /drone/app
  - ./app

- name: test
  image: redis
  commands:
  - sleep 5
  - echo $REDIS_SERVICE_HOST jjajaa
  - redis-cli -h $REDIS_SERVICE_HOST ping

services:
- name: redis
  image: redis
  ports:
  - 6379