kind: pipeline
name: default

steps:
- name: foo
  image: alpine
  commands:
  - touch hello.txt

- name: bar
  image: alpine
  commands:
  - ls hello.txt

- name: build
  image: golang:alpine
  environment:
    - KEY=VALUE
  secrets: [key1, key2]
  commands:
    - echo $$KEY
    - pwd
    - ls
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
    - ./app